app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#app_homepage:
#    path:     /homepage
#    defaults: { _controller: :Default:homepage }